accident/urls.py
from django.conf.urls import url, include
from django.contrib import admin


from api.views import IssueViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'issues', IssueViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^', include('issue.urls')),
    url(r'^', include(router.urls)),
]

issue/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from issue import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^registrar-incidencia/$', views.add_issue, name='add_issue'),
    url(r'^listado-incidencias/$', views.issue_list, name='issue_list'),
    url(r'^incidencia/(?P<issue_uuid>[-\w]+)/$', views.issue_view, name='issue_view'),
]

issue/models.py
import datetime
import uuid

from decimal import Decimal
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User, Group
from django.urls.base import reverse


class Issue(models.Model):
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    uuid = models.UUIDField(default=uuid.uuid4)

    TYPE_CHOICES = (
        ("Casa", "Casa"),
        ("Objeto", "Objeto"),
        ("Auto", "Auto")
    )

    STATES = (
        ("Nuevo", "Nuevo"),
        ("Tomado", "Tomado"),
        ("Visado", "Visado"),
        ("Presupuestado", "Presupuestado"),
        ("Aprobado", "Aprobado"),
        ("Desaprobado", "Desaprobado")
    )

    user = models.ForeignKey(User)
    issue_date = models.DateField()

    visado_date = models.DateField(null=True, blank=True)
    revisado_date = models.DateField(null=True, blank=True)
    tomado_date = models.DateField(null=True, blank=True)
    aprobado_date = models.DateField(null=True, blank=True)
    desaprobado_date = models.DateField(null=True, blank=True)

    type = models.CharField(max_length=255, choices=TYPE_CHOICES, default="Objeto")
    state = models.CharField(max_length=255, choices=STATES, default="Nuevo")
    description = models.TextField(default="")
    monto = models.DecimalField(decimal_places=2, max_digits=10, default=Decimal("0.0"))
    case_id = models.CharField(max_length=30, default="")

    def get_objects(self):
        return self.issueobject_set.all()

    @classmethod
    def get_by_uuid(self, uuid):
        return Issue.objects.first() #TODO

    def get_unique_url(self):
        return settings.DOMAIN + reverse("issue_view", args=[self.uuid])

    def save(self, *args, **kwargs):
        if self.state == "Tomado" and self.tomado_date is None:
            self.tomado_date = datetime.date.today()
        if self.state == "Visado" and self.visado_date is None:
            self.visado_date = datetime.date.today()
        if self.state == "Revisado" and self.revisado_date is None:
            self.revisado_date = datetime.date.today()
        if self.state == "Aprobado" and self.aprobado_date is None:
            self.aprobado_date= datetime.date.today()
        if self.state == "Desaprobado" and self.desaprobado_date is None:
            self.desaprobado_date = datetime.date.today()

        return super(Issue, self).save(*args, **kwargs)

class IssueObject(models.Model):
    issue = models.ForeignKey(Issue)
    name = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField(default=1)
    description = models.TextField(default="")

api/views.py
import requests

from rest_framework import viewsets, mixins
from rest_framework.decorators import detail_route
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response

from issue.models import Issue
from api.serializers import IssueSerializer, IssueSerializerPatch


class IssueViewSet(
                    mixins.RetrieveModelMixin,
                    mixins.ListModelMixin,
                    mixins.UpdateModelMixin,
                    mixins.CreateModelMixin,
                    viewsets.GenericViewSet
                  ):

    permission_classes = (IsAuthenticated,)

    serializer_class = IssueSerializer
    serializer_class_patch = IssueSerializerPatch

    queryset = Issue.objects.all()

    def get_serializer_class(self):
        if self.request.method in ('PATCH',):
            return self.serializer_class_patch

        return self.serializer_class

    def check_permissions(self, request):
        if "pk" in self.kwargs:
            try:
                return Issue.objects.get(uuid=self.kwargs["pk"])
            except Exception:
                pass
        return super(IssueViewSet, self).check_permissions(request)

    def get_object(self):
        if "pk" in self.kwargs:
            try:
                return Issue.objects.get(uuid=self.kwargs["pk"])
            except Exception:
                pass
        return super(IssueViewSet, self).get_object()

    def get_queryset(self):
        state = self.request.GET.get('state')
        case_id = self.request.GET.get('case_id')

        if self.request.user.is_staff:
            qs = Issue.objects.all()

            if state is not None:
                qs = qs.filter(state=state)

            if case_id is not None:
                qs = qs.filter(case_id=case_id)

            return qs

        return Issue.objects.filter(user=self.request.user)

    @detail_route(methods=["get"])
    def images(self, *args, **kwargs):
        issue = self.get_object()
        r = requests.get("https://dssd-grupo26.herokuapp.com/upload/?metadata=%s" % issue.id)
        try:
            data = r.json()
            return Response(list(map(lambda x: x["link"], data)))
        except Exception:
            return Response([])

issue/views.py
from django.shortcuts import render, redirect
from django.utils.deprecation import MiddlewareMixin
from rest_framework.authentication import BaseAuthentication
from django.contrib.auth.models import User
from django.conf import settings
from rest_framework import exceptions



def home(request):
    if request.user.is_authenticated():
        return redirect(issue_list)
    return render(request, "base.html", {})

def add_issue(request):
    if not request.user.is_authenticated():
        return redirect(home)

    return render(request, "issue/add_issue.html", {
    })


def issue_view(request, issue_uuid):
    return render(request, "issue/view_issue.html", {
        "issue_url": "/issues/%s/" % issue_uuid
    })



def issue_list(request):
    if not request.user.is_authenticated():
        return redirect(home)

    return render(request, "issue/issue_list.html", {
    })


class DisableCSRF(MiddlewareMixin):
    # for testing
    def process_request(self, request):
        setattr(request, '_dont_enforce_csrf_checks', True)


class TokenBonita(BaseAuthentication):
    """
    HTTP Basic authentication against username/password.
    """
    www_authenticate_realm = 'api'

    def authenticate(self, request):
        if request.GET.get("token") == settings.BONITA_TOKEN:
            return (User.objects.filter(is_staff=True).first(), None)
        elif "token" in request.GET:
            raise exceptions.AuthenticationFailed("Auth error")

issue/templates/issue/add_issue.html
{% extends "base.html" %}
{% block content %}

  <h1 class="title">Registrar Incidencia</h1>

  <form action="." method="post" id="app">
    <div class="field">
      <label class="label ">Tipo de incidencia</label>
      <div class="control ">
        <span class="select">
          <select v-model="type" name="type" id="id_type">
            <option value="Casa">Casa</option>
            <option value="Objeto" selected>Objeto</option>
            <option value="Auto">Auto</option>
          </select>
        </span>
      </div>
    </div>

    <div class="field">
      <label class="label">Fecha de incidente</label>
      <div class="control ">
        <input v-model="issue_date" name="date" required id="id_date" type="date" />
        <div v-if="submitted && !issue_date" class="help is-danger">
          Este campo es requerido
        </div>
      </div>
    </div>

    <div class="field">
      <label class="label">Descripción</label>
      <div class="control ">
        <textarea v-model="description" name="description" required id="id_description" cols="40" rows="10" class="textarea"></textarea>
        <div v-if="submitted && description.length == 0" class="help is-danger">
          Este campo es requerido
        </div>
      </div>
    </div>

    <div class="box" v-for="(issueObject, index) in objects">

      <div class="level">
        <div class="level-left">
          <div class="level-item">
            <h4 class="title is-4">Objeto</h4>

          </div>

        </div>
        <div class="level-right">
          <div class="level-item"></div>
          <a v-if="objects.length > 1" v-on:click="removeObject(index)" href="#">Eliminar</a>
        </div>
      </div>


      <div class="field is-horizontal">
        <div class="field-label" >
          <label class="label">Nombre</label>
        </div>
        <div class="field-body">
          <div class="control ">
            <input v-model="issueObject.name" type="text" required class="input" />
            <div v-if="submitted && issueObject.name.length == 0" class="help is-danger">
              Este campo es requerido
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label" >
          <label class="label">Cantidad</label>
        </div>
        <div class="field-body">
          <div class="control ">
            <input v-model="issueObject.quantity" type="number" required class="input" />
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label" >
          <label class="label">Descripción</label>
        </div>
        <div class="field-body">
          <div class="control ">
            <textarea v-model="issueObject.description" required cols="40" rows="5" class="textarea"></textarea>
            <div v-if="submitted && issueObject.description.length == 0" class="help is-danger">
              Este campo es requerido
            </div>

          </div>
        </div>
      </div>
    </div>

    <div class="field is-grouped">
      <div class="control">
        <div class="button is-info" v-on:click="addObject">Agregar Objecto</div>
      </div>
      <div class="control">
        <div class="button is-primary" v-bind:class="{'is-loading': loading }" v-on:click="submitIssue">Enviar</div>
      </div>
    </div>

  </form>

  <script>
    var app = new Vue({
      el: '#app',
      data: {
        issueDone: null,
        type: "Casa",
        description: "",
        loading: false,
        submitted: false,
        issue_date: null,
        objects: [
          { description: "", quantity: 1, name: "" }
        ]
      },
      methods: {
        addObject: function(){
          this.objects.push({
            description: "", quantity: 1, name: ""
          })
        },
        removeObject: function (position) {
          this.objects.splice(position, 1);
        },

        submitIssue: function () {
          var that = this;
          if (this.loading) {
            return
          }
          this.loading = true;

          this.$http.post('/issues/', {
            type: this.type,
            description: this.description,
            objects: this.objects,
            issue_date: this.issue_date
          }).then(function success (response) {
            this.submitted = true;
            window.location.replace(response.data.url);
            this.issueDone = response.data;
          }, function error () {
            this.submitted = true;
            that.loading = false;
          });
        }

      }
    })
  </script>

{% endblock %}

issue/templates/issue/issue_component.html
{% verbatim %}
<script type="text/x-template" id="issue-template">

  <div class="card" style="margin-bottom: 20px">
    <header class="card-header">
      <p class="card-header-title">
        <span style="padding-right: 5px">Incidencia {{ issue.id }}</span> <a v-bind:href="issue.url">Enlace Permanente</a>
      </p>
    </header>
    <div class="card-content">
      <div class="content">
        <table class="table is-bordered is-fullwidth">
          <tbody>
          <tr>
            <th style="width: 50px">Tipo:</th>
            <td>{{ issue.type }}</td>
          </tr>
          <tr>
            <th style="width: 50px">Descripción:</th>
            <td>{{ issue.description }}</td>
          </tr>
          <tr>
            <th style="width: 50px">Estado:</th>
            <td>{{ issue.state }}</td>
          </tr>
          <tr v-if="issue.monto>0">
            <th style="width: 50px">Monto:</th>
            <td>{{ issue.monto }}</td>
          </tr>
          </tbody>
        </table>

        <table v-if="issue.objects.length > 0" class="table is-bordered is-fullwidth">
          <thead>
          <tr>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Descripción</th>
          </tr>
          </thead>

          <tbody>
          <tr v-for="obj in issue.objects">
            <td>{{ obj.name}}</td>
            <td>{{ obj.quantity}}</td>
            <td>{{ obj.description}}</td>
          </tr>
          </tbody>
        </table>

        <div v-if="!loadedImages" v-bind:class="{'is-loading': loading }" v-on:click="getImages" class="button">Cargar Imágenes</div>

        <div v-if="loadedImages && images.length == 0">
          No hay contenido disponible
        </div>

        <div v-if="loadedImages" v-for="image in images">
          <img v-bind:src="image" width="200" style="width: 200px; height: auto; display: block">
        </div>

      </div>
    </div>
  </div>
</script>
{% endverbatim %}

<script>
  Vue.component('issue', {
    template: '#issue-template',
    props: ['issue'],
    data: function () {
      return {
        images: null,
        loadedImages: false,
        loading: false
      }
    },
    methods: {
      getImages: function () {
        var that = this;
        if (this.loading) {
          return
        }
        this.loading = true;

        this.$http.get('/issues/'+this.issue.id+'/images/').then(function success (response) {
          that.images = response.data;
          that.loadedImages = true;
        });
      }
    }
  });
</script>

issue/templates/issue/issue_list.html
{% extends "base.html" %}
{% block content %}
  <div id="app">
    <div v-if="issues.length == 0">
      No se registran incidencias
    </div>
    <div v-for="issue in issues">
      <issue v-bind:issue="issue"></issue>
    </div>
  </div>

  {% include "issue/issue_component.html" %}
  <script>
    var app = new Vue({
      el: '#app',
      data: {
        issues: []
      },
      created: function () {
        this.getIssues();
      },
      methods: {
        getIssues: function () {
          var that = this;
          this.$http.get('/issues/').then(function success (response) {
            this.issues = response.data;
          });
        }
      }
    })
  </script>

{% endblock %}

issue/templates/issue/view_issue.html
{% extends "base.html" %}
{% block content %}

  <div id="app">
    <div v-if="issue">
      <issue v-bind:issue="issue"></issue>
    </div>
  </div>

  {% include "issue/issue_component.html" %}

  <script>
    var app = new Vue({
      el: '#app',
      data: {
        issue: undefined
      },
      created: function () {
        this.getIssue();
      },
      methods: {
        getIssue: function () {
          var that = this;
          this.$http.get('{{ issue_url }}').then(function success (response) {
            this.issue = response.data;
          });
        }
      }
    })
  </script>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Issue tracker</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.1/css/bulma.min.css">
  <script src="https://unpkg.com/vue"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue-resource@1.3.4"></script>
</head>

<body>

<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        DSSD 2017
      </h1>
      <h2 class="subtitle">
        Incidencias
      </h2>
    </div>
  </div>
</section>




<section class="section">
  <div class="container">

    <div class="columns">
      <div class="column is-one-third">

        <aside class="menu">
          {% if user.is_authenticated %}
            <p class="menu-label">
              General
            </p>
            <ul class="menu-list">
              <li><a href="{% url "issue_list" %}">Mis Incidencias</a></li>
              <li><a href="{% url "add_issue" %}">Registar Incidencia</a></li>
            </ul>
            <p class="menu-label">
              Usuario
            </p>
            <ul class="menu-list">
              <li><a href="/logout/?next=/">Salir</a></li>
            </ul>
          {% else %}
            <p class="menu-label">
              Usuario
            </p>
            <ul class="menu-list">
              <li><a href="/login/?next=/">Ingresar</a></li>
            </ul>
          {% endif %}
        </aside>
      </div>

      <div class="column">
        {% block content %}
        {% endblock %}
      </div>
    </div>

  </div>
</section>
</body>
</html>